import { getPublicCred } from "./public-creds.js";

export const OAUTH_PROVIDERS = {
  github: {
    name: "GitHub Copilot",
    type: "device_code" as const,
    clientId: getPublicCred("github_copilot_id", "GITHUB_OAUTH_CLIENT_ID"),
    deviceCodeUrl: "https://github.com/login/device/code",
    tokenUrl: "https://github.com/login/oauth/access_token",
    userInfoUrl: "https://api.github.com/user",
    copilotTokenUrl: "https://api.github.com/copilot_internal/v2/token",
    scopes: "read:user",
    apiVersion: "2023-07-07",
    userAgent: "GitHubCopilot/1.0",
    defaultModels: [
      { id: "gpt-4o", name: "GPT-4o (Copilot)" },
      { id: "claude-3.5-sonnet", name: "Claude 3.5 Sonnet (Copilot)" },
      { id: "o1-mini", name: "o1-mini (Copilot)" },
      { id: "o3-mini", name: "o3-mini (Copilot)" },
    ],
  },
  antigravity: {
    name: "Google Antigravity (Cloud Code)",
    type: "authorization_code" as const,
    clientId: getPublicCred("antigravity_id", "ANTIGRAVITY_OAUTH_CLIENT_ID"),
    clientSecret: getPublicCred("antigravity_alt", "ANTIGRAVITY_OAUTH_CLIENT_SECRET"),
    authorizeUrl: "https://accounts.google.com/o/oauth2/v2/auth",
    tokenUrl: "https://oauth2.googleapis.com/token",
    userInfoUrl: "https://www.googleapis.com/oauth2/v1/userinfo",
    scopes: [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/userinfo.email",
      "https://www.googleapis.com/auth/userinfo.profile",
    ],
    defaultModels: [
      { id: "gemini-3.7-flash-high", name: "Gemini 3.7 Flash (High)" },
      { id: "gemini-3.7-flash-medium", name: "Gemini 3.7 Flash (Medium)" },
      { id: "gemini-3.7-flash-low", name: "Gemini 3.7 Flash (Low)" },
      { id: "gemini-pro-agent", name: "Gemini 3.1 Pro (High)" },
      { id: "gemini-3.1-pro-low", name: "Gemini 3.1 Pro (Low)" },
      { id: "gemini-3.1-flash-lite", name: "Gemini 3.1 Flash Lite" },
      { id: "claude-opus-4-6-thinking", name: "Claude Opus 4.6 (Thinking)" },
      { id: "claude-sonnet-4-6", name: "Claude Sonnet 4.6 (Thinking)" },
      { id: "claude-3-5-sonnet-v2", name: "Claude 3.5 Sonnet v2" },
      { id: "gpt-oss-120b-medium", name: "GPT-OSS 120B (Medium)" },
      { id: "gemini-2.5-pro", name: "Gemini 2.5 Pro" },
      { id: "gemini-2.5-flash", name: "Gemini 2.5 Flash" },
      { id: "gemini-2.0-flash", name: "Gemini 2.0 Flash" },
    ],
  },
  claude: {
    name: "Claude Code CLI",
    type: "authorization_code" as const,
    clientId: getPublicCred("claude_id", "CLAUDE_OAUTH_CLIENT_ID"),
    authorizeUrl: "https://claude.ai/oauth/authorize",
    tokenUrl: "https://api.anthropic.com/v1/oauth/token",
    scopes: [
      "org:create_api_key",
      "user:profile",
      "user:inference",
      "user:sessions:claude_code",
    ],
    defaultModels: [
      { id: "claude-3-7-sonnet-latest", name: "Claude 3.7 Sonnet" },
      { id: "claude-3-5-sonnet-latest", name: "Claude 3.5 Sonnet" },
      { id: "claude-3-5-haiku-latest", name: "Claude 3.5 Haiku" },
    ],
  },
  grok: {
    name: "xAI Grok Build",
    type: "device_code" as const,
    clientId: getPublicCred("grok_id", "GROK_OAUTH_CLIENT_ID"),
    issuer: "https://auth.x.ai",
    deviceCodeUrl: "https://auth.x.ai/oauth2/device/code",
    tokenUrl: "https://auth.x.ai/oauth2/token",
    scopes: "openid profile email offline_access grok-cli:access api:access",
    defaultModels: [
      { id: "grok-2", name: "Grok 2" },
      { id: "grok-2-vision", name: "Grok 2 Vision" },
      { id: "grok-beta", name: "Grok Beta" },
      { id: "grok-vision-beta", name: "Grok Vision Beta" },
      { id: "grok-3", name: "Grok 3" },
      { id: "grok-3-mini", name: "Grok 3 Mini" },
    ],
  },
  kimi: {
    name: "Kimi Coding CLI",
    type: "device_code" as const,
    clientId: getPublicCred("kimi_id", "KIMI_CODING_OAUTH_CLIENT_ID"),
    deviceCodeUrl: "https://auth.kimi.com/api/oauth/device_authorization",
    tokenUrl: "https://auth.kimi.com/api/oauth/token",
    scopes: "offline_access",
    defaultModels: [
      { id: "kimi-k1.5", name: "Kimi k1.5 (Coding)" },
      { id: "moonshot-v1-128k", name: "Moonshot v1 128k" },
    ],
  },
  codex: {
    name: "OpenAI Codex CLI",
    type: "authorization_code" as const,
    clientId: getPublicCred("codex_id", "CODEX_OAUTH_CLIENT_ID"),
    authorizeUrl: "https://auth.openai.com/oauth/authorize",
    tokenUrl: "https://auth.openai.com/oauth/token",
    scope: "openid profile email offline_access",
    defaultModels: [
      { id: "gpt-4o", name: "GPT-4o (Codex)" },
      { id: "o1-preview", name: "o1 Preview" },
      { id: "o3-mini", name: "o3 Mini" },
    ],
  },
} as const;

export type OAuthProviderKey = keyof typeof OAUTH_PROVIDERS;
